{
    'name': 'Collect map',
    'version': '1.0',
    'depends': ['base', 'fleet', 'mail', 'hr', 'auth_signup', 'web'],
    'sequence': 20,
    'author': 'Oumaima',
    'category': 'Fleet Management',
    'summary': 'Collect module for managing Medical Trash collection',
    'data': [
        'data/tracking_cron.xml',
        'data/bs_sequence.xml',
        'security/ir.model.access.csv',
        'views/collect_vehicle_view.xml',
        'views/collect_partner_view.xml',
        'views/collect_convoyeur_views.xml',
        'wizard/traccar_device_details_wizard_view.xml',
        'wizard/traccar_track_history_wizard_view.xml',
        'wizard/deletion_confirmation_wizard_view.xml',
        'views/collect_bordereau_views.xml',
        'views/collect_action_menu.xml',
        'views/collect_menu.xml',
        'wizard/realtime_tracking_wizard_view.xml',
        'views/collect_contrat.xml',
        'views/collect_planning_mensuel.xml',
        'views/collect_planification_calendrier.xml',
        'views/collect_planning_jour.xml',


    ],
    'assets': {
        'web.assets_backend': [
            'collecte_module/static/src/xml/map_templates.xml',
            'collecte_module/static/src/xml/map_client_position_template.xml',
            'collecte_module/static/src/js/client_position_map.js',
            'collecte_module/static/src/js/traccar_history_map.js',
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
            'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
             'collecte_module/static/src/js/client_map_view.js',
            'collecte_module/static/src/xml/client_map_template.xml',
            'collecte_module/static/src/js/traccar_realtime_tracking_map.js',
        'collecte_module/static/src/xml/realtime_tracking_map_template.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
